apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        name: javawebapp
    spec:
      containers:
      - image: kammula280/javawebapp
        name: javawebappcontainer
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60 
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
spec:
  type: LoadBalancer
  selector:
    name: javawebapp
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpajavawebappdeployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name : javawebappdeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 75
      type: Resource
